# Generated by Django 5.1.2 on 2024-10-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanchonete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('endereco', models.CharField(max_length=255)),
                ('horario_segunda_inicio', models.TimeField(blank=True, null=True)),
                ('horario_segunda_fim', models.TimeField(blank=True, null=True)),
                ('horario_terca_inicio', models.TimeField(blank=True, null=True)),
                ('horario_terca_fim', models.TimeField(blank=True, null=True)),
                ('horario_quarta_inicio', models.TimeField(blank=True, null=True)),
                ('horario_quarta_fim', models.TimeField(blank=True, null=True)),
                ('horario_quinta_inicio', models.TimeField(blank=True, null=True)),
                ('horario_quinta_fim', models.TimeField(blank=True, null=True)),
                ('horario_sexta_inicio', models.TimeField(blank=True, null=True)),
                ('horario_sexta_fim', models.TimeField(blank=True, null=True)),
                ('horario_sabado_inicio', models.TimeField(blank=True, null=True)),
                ('horario_sabado_fim', models.TimeField(blank=True, null=True)),
                ('horario_domingo_inicio', models.TimeField(blank=True, null=True)),
                ('horario_domingo_fim', models.TimeField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
